export const CREATE_REVIEW_REQUEST = "CREATE_REVIEW_REQUEST";
export const CREATE_REVIEW_SUCCESS = "CREATE_REVIEW_SUCCESS";
export const CREATE_REVIEW_RESET = "CREATE_REVIEW_RESET";
export const CREATE_REVIEW_FAIL = "CREATE_REVIEW_FAIL";


export const ADMIN_ALL_REVIEW_REQUEST = "ADMIN_ALL_REVIEW_REQUEST";
export const ADMIN_ALL_REVIEW_SUCCESS = "ADMIN_ALL_REVIEW_SUCCESS";
export const ADMIN_ALL_REVIEW_RESET = "ADMIN_ALL_REVIEW_RESET";
export const ADMIN_ALL_REVIEW_FAIL = "ADMIN_ALL_REVIEW_FAIL";

export const ADMIN_DELETE_REVIEW_REQUEST = "ADMIN_DELETE_REVIEW_REQUEST";
export const ADMIN_DELETE_REVIEW_SUCCESS = "ADMIN_DELETE_REVIEW_SUCCESS";
export const ADMIN_DELETE_REVIEW_RESET = "ADMIN_DELETE_REVIEW_RESET";
export const ADMIN_DELETE_REVIEW_FAIL = "ADMIN_DELETE_REVIEW_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";