export const CLEAR_ERRORS = "CLEAR_ERRORS";

export const APPLY_VOUCHER_REQUEST = "APPLY_VOUCHER_REQUEST";
export const APPLY_VOUCHER_SUCCESS = "APPLY_VOUCHER_SUCCESS";
export const APPLY_VOUCHER_FAIL = "APPLY_VOUCHER_FAIL";

export const REMOVE_VOUCHER_REQUEST = "REMOVE_VOUCHER_REQUEST";
export const REMOVE_VOUCHER_SUCCESS = "REMOVE_VOUCHER_SUCCESS";
export const REMOVE_VOUCHER_FAIL = "REMOVE_VOUCHER_FAIL";

export const CREATE_VOUCHER_REQUEST = 'CREATE_VOUCHER_REQUEST';
export const CREATE_VOUCHER_SUCCESS = 'CREATE_VOUCHER_SUCCESS';
export const CREATE_VOUCHER_FAIL = 'CREATE_VOUCHER_FAIL';
export const CREATE_VOUCHER_RESET = "CREATE_VOUCHER_RESET";

export const GET_ALL_VOUCHERS_REQUEST = 'GET_ALL_VOUCHERS_REQUEST';
export const GET_ALL_VOUCHERS_SUCCESS = 'GET_ALL_VOUCHERS_SUCCESS';
export const GET_ALL_VOUCHERS_FAIL = 'GET_ALL_VOUCHERS_FAIL';

export const VOUCHER_DETAILS_REQUEST = "VOUCHER_DETAILS_REQUEST";
export const VOUCHER_DETAILS_SUCCESS = "VOUCHER_DETAILS_SUCCESS";
export const VOUCHER_DETAILS_FAIL = "VOUCHER_DETAILS_FAIL";

export const UPDATE_VOUCHER_REQUEST = 'UPDATE_VOUCHER_REQUEST';
export const UPDATE_VOUCHER_SUCCESS = 'UPDATE_VOUCHER_SUCCESS';
export const UPDATE_VOUCHER_FAIL = 'UPDATE_VOUCHER_FAIL';
export const UPDATE_VOUCHER_RESET = 'UPDATE_VOUCHER_RESET';

export const DELETE_VOUCHER_REQUEST = 'DELETE_VOUCHER_REQUEST';
export const DELETE_VOUCHER_SUCCESS = 'DELETE_VOUCHER_SUCCESS';
export const DELETE_VOUCHER_FAIL = 'DELETE_VOUCHER_FAIL';
export const DELETE_VOUCHER_RESET = 'DELETE_VOUCHER_RESET';

export const GET_VOUCHER_REQUEST = 'GET_VOUCHER_REQUEST';
export const GET_VOUCHER_SUCCESS = 'GET_VOUCHER_SUCCESS';
export const GET_VOUCHER_FAIL = 'GET_VOUCHER_FAIL';

