export const CLEAR_ERRORS = "CLEAR_ERRORS";

export const APPLY_VOUCHER_REQUEST = "APPLY_VOUCHER_REQUEST";
export const APPLY_VOUCHER_SUCCESS = "APPLY_VOUCHER_SUCCESS";
export const APPLY_VOUCHER_FAIL = "APPLY_VOUCHER_FAIL";

export const REMOVE_VOUCHER_REQUEST = "REMOVE_VOUCHER_REQUEST";
export const REMOVE_VOUCHER_SUCCESS = "REMOVE_VOUCHER_SUCCESS";
export const REMOVE_VOUCHER_FAIL = "REMOVE_VOUCHER_FAIL";
